name: base
config: base
platform: linux
os: debian
version: '12'
release: bookworm
sections:
    - name: core
      type: debian_packages
      pre_install: |
        sudo apt-get update && sudo apt-get dist-upgrade -y
      install:
        - build-essential
        - ncdu
        - htop
        - vim
        - exuberant-ctags
        - tig
        - bmon
        - pv
        - rpl
        - unzip
        - p7zip-full
        - open-vm-tools
      purge:
        - snapd
      post_install: |
        mkdir -p ~/.host-shared

    - name: python
      type: debian_packages
      install:
        - python3-dev
        - python3-setuptools
        - python3-pip

    - name: py_modules
      type: python_packages
      install:
          - wheel
          - virtualenv
          - ipython
          - cython
          - psycopg2
          - pgcli
          - grin
          - isort
          - pylint
          - radon
          - autopep8
          - glances
          - ranger-fm

    - name: database
      type: debian_packages
      pre_install: |
        # Add PostgreSQL repository for Debian 12 (Bookworm)
        sudo apt install -y curl ca-certificates
        sudo install -d /usr/share/postgresql-common/pgdg
        sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
        sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        sudo apt update
      install:
        - libpq-dev
        - postgresql-client-15
        - postgresql-15
        - postgresql-contrib
        - postgresql-plpython3-15
        - luajit
      post_install: |
        sudo -u postgres createuser -s $USER
        sudo -u postgres createdb $USER

    - name: gui
      type: debian_packages
      install:
          - xorg
          - xserver-xorg-input-all
          - open-vm-tools-desktop
          - fonts-dejavu
          - gnome-icon-theme
          - awesome
          - i3
          - roxterm
          - lxappearance
          - gtk2-engines
          - conky
          - scite
          - gtkorphan
          - fslint
          - bleachbit
