
theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false
gutters = ["diff", "diagnostics", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


[keys.normal]
"{" = "page_cursor_half_up"
"}" = "page_cursor_half_down"

